"""init: create tables tenant utilisateur ressource modele_evenement demande devis

Revision ID: a305b37f20c2
Revises: 
Create Date: 2026-09-04 11:44:44.149554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a305b37f20c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('coordonnees', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('demande',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('identifiant_prospect', sa.String(length=255), nullable=True),
    sa.Column('etat', sa.String(length=20), nullable=False),
    sa.Column('besoin', sa.JSON(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demande_tenant_id'), 'demande', ['tenant_id'], unique=False)
    op.create_table('modele_evenement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lignes_par_defaut', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modele_evenement_tenant_id'), 'modele_evenement', ['tenant_id'], unique=False)
    op.create_table('ressource',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('secteur', sa.String(length=50), nullable=False),
    sa.Column('unite_facturation', sa.String(length=20), nullable=False),
    sa.Column('prix_unitaire', sa.Integer(), nullable=False),
    sa.Column('attributs', sa.JSON(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ressource_tenant_id'), 'ressource', ['tenant_id'], unique=False)
    op.create_table('utilisateur',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hache', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateur_tenant_id'), 'utilisateur', ['tenant_id'], unique=False)
    op.create_table('devis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('demande_id', sa.String(length=36), nullable=False),
    sa.Column('lignes', sa.JSON(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=False),
    sa.Column('date_emission', sa.DateTime(), nullable=False),
    sa.Column('date_validite', sa.DateTime(), nullable=False),
    sa.Column('chemin_pdf', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['demande_id'], ['demande.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devis_demande_id'), 'devis', ['demande_id'], unique=False)
    op.create_index(op.f('ix_devis_tenant_id'), 'devis', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devis_tenant_id'), table_name='devis')
    op.drop_index(op.f('ix_devis_demande_id'), table_name='devis')
    op.drop_table('devis')
    op.drop_index(op.f('ix_utilisateur_tenant_id'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_index(op.f('ix_ressource_tenant_id'), table_name='ressource')
    op.drop_table('ressource')
    op.drop_index(op.f('ix_modele_evenement_tenant_id'), table_name='modele_evenement')
    op.drop_table('modele_evenement')
    op.drop_index(op.f('ix_demande_tenant_id'), table_name='demande')
    op.drop_table('demande')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_table('tenant')
    # ### end Alembic commands ###
