"""ajoute la table prospect, remplace identifiant_prospect par prospect_id

Revision ID: d3bb338e15c7
Revises: a305b37f20c2
Create Date: 2026-09-07 12:29:50.939796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bb338e15c7'
down_revision: Union[str, Sequence[str], None] = 'a305b37f20c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prospect',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('consentement_contact', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospect_tenant_id'), 'prospect', ['tenant_id'], unique=False)
    op.add_column('demande', sa.Column('prospect_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_demande_prospect_id'), 'demande', ['prospect_id'], unique=False)
    op.create_foreign_key(None, 'demande', 'prospect', ['prospect_id'], ['id'])
    op.drop_column('demande', 'identifiant_prospect')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demande', sa.Column('identifiant_prospect', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'demande', type_='foreignkey')
    op.drop_index(op.f('ix_demande_prospect_id'), table_name='demande')
    op.drop_column('demande', 'prospect_id')
    op.drop_index(op.f('ix_prospect_tenant_id'), table_name='prospect')
    op.drop_table('prospect')
    # ### end Alembic commands ###
